project:
  title: "Kansas City Mental Health Survey"
  type: website
  output-dir: "../../docs"

title: "Kansas City Mental Health Survey"
subtitle: "2024 Report"
author:
  name: |
    | Kansas City Health Department
    | Office of Population Health Science



